name: Some Release Event

on:
  release:
  workflow_dispatch:
  push:

env:
  DEPLOY_ENV: prod

jobs:
  do-whatever-things:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Say hello
        run: echo ${GITHUB_REF} did something
      - name: Shout it out
        run: jq < ${GITHUB_EVENT_PATH}
      - name: Find releases URL
        run: echo RELEASE_URL=$(jq < ${GITHUB_EVENT_PATH} '.repository.releases_url' | sed -e 's/{\/id}//' ) >> $GITHUB_ENV
      - name: List releases
        run: echo "Attempting to retrieve releases from '$RELEASE_URL'; curl $RELEASE_URL | jq
      - name: Get an arbitrary release
        run: curl $RELEASE_URL/tags/v0.4.1 | jq
      
