name: Pre-release Event

on:
  release:
    types: [prereleased]

env:
  DEPLOY_ENV: prod

jobs:
  pre-release-precheck:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.release.assets.*.name, 'MyFile.txt') }}
    steps:
      - name: LOL
        working-directory: /
        run: echo "This upload is going to fail."
  do-prerelease-things:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Say hello
        run: echo ${GITHUB_REF} is not yet released
      - name: Make a file
        run: echo $(date) is when this was created for ${GITHUB_REF} > release-file.txt
      - name: Add upload URL to environment
        run: echo UPLOAD_URL=$(echo '${{github.event.release.upload_url}}' | sed -e 's/{?name,label}//') >> $GITHUB_ENV
      - name: Mess with that
        run: echo $UPLOAD_URL
      - name: Attempt an upload
        run: |
          DOWNLOAD_URL=$(curl -f -s -X POST --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --data-binary @release-file.txt \
          --header "Accept: application/vnd.github.v3+json" \
          --header "Content-type: text/plain" \
          "$UPLOAD_URL?name=MyFile.txt&label=Fancy%20File" | jq .url)
          [[ -n "$DOWNLOAD_URL" ]] && echo Uploaded file to $DOWNLOAD_URL 
