name: Deploy Prod

on:
  release:
    types: [released]

env:
  DEPLOY_ENV: prod

jobs:
  do-release-things:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Say hello
        run: echo ${GITHUB_REF} is released
