name: Release Event

on:
  release:
    types: [released]

env:
  DEPLOY_ENV: prod

jobs:
  do-release-things:
    runs-on: ubuntu-latest
    outputs:
      stuff: ${{steps.store-things.outputs.file-content}}
    steps:
      - uses: actions/checkout@v2
      - name: Say hello
        run: echo ${GITHUB_REF} is released
      - name: Get download URL
        run: echo DOWNLOAD=$(jq -r '.release.assets[] | select(.label=="Fancy File") | .url' < ${GITHUB_EVENT_PATH}) >> $GITHUB_ENV
      - name: Fetch it
        run: |
          curl -L -v \
           --header 'Accept: application/octet-stream' \
           --header 'Authorization: Bearer ${{secrets.GITHUB_TOKEN}}' \
           $DOWNLOAD \
           > releasefile.txt
      - name: Look at it
        id: store-things
        run: echo "::set-output name=file-content::$(cat releasefile.txt)"
  do-followup-things:
    runs-on: ubuntu-latest 
    needs: do-release-things
    steps:
      - name: Fetch that output
        working-directory: /
        run: |
          echo "File content follows"
          echo ${{needs.do-release-things.outputs.stuff}}
